<?php 
/**
 * Copyright (c) 2025 SCHENCK Simon
 * 
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 * @copyright     Copyright (c) SCHENCK Simon
 *
 */

namespace SkankyDev\Utilities;

use SkankyDev\Model\Document\EmbeddedDocument;

/**
 * CSRF / one-time token with an optional time-to-live check.
 * Generates a cryptographically random hex token on construction.
 * Extends EmbeddedDocument pour pouvoir être stocké tel quel comme sous-document
 * (ex. User.reset_token, User.remember_token).
 */
class Token extends EmbeddedDocument {

	/** 32-character hex string generated by random_bytes(). */
	public string $value = '';

	/** Unix timestamp of when the token was created. */
	public int $time = 0;

	/**
	 * Generates a new random token and records the current time.
	 * $data (ex. reconstruction manuelle) peut écraser value/time via fill().
	 */
	public function __construct(array $data = []) {
		$this->value = bin2hex(random_bytes(16));
		$this->time  = time();
		parent::__construct($data);
	}

	/**
	 * Returns true if the token has not yet expired.
	 * @param int $life lifetime in seconds (defaults to TIME_HOUR constant)
	 */
	public function checkTime(int $life = TIME_HOUR): bool {
		$tokenExpir = $this->time + $life;
		return ($tokenExpir > time());
	}

	/**
	 * Returns true if the provided value matches the token.
	 * Uses strict comparison (no type coercion).
	 */
	public function checkValue(string $value): bool {
		return ($this->value === $value);
	}

	/** Returns the raw token string. */
	public function getToken(): string {
		return $this->value;
	}
}

